image: python:latest

services:
  - alias: ubuntu18
    name: rastasheep/ubuntu-sshd:18.04
  - alias: centos7
    name: indigodatacloud/centos-sshd:7

stages:
  - test
  - test_readme_procedure
  - medium_test
  - release

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -r dev-requirements.txt
  - python -V
  - which python
  - which pip

pip_install:
  stage: test_readme_procedure
  script:
    - pip install -U .
    - python -m sshkernel install
    - pip freeze | grep sshkernel
    - jupyter kernelspec list | grep ssh

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37
  artifacts:
    paths:
    - htmlcov
    expire_in: 1 month

run_papermill:
  image: python:3.7
  stage: medium_test
  script:
    - pip install .
    - pip install papermill
    - python ./tests/integration/setup.py
    - python -m unittest discover tests/integration 
  artifacts:
    paths:
      - ./tests/integration/out
    expire_in: 1 month

release_pypi_package:
  image: python:3.7
  stage: release
  script: tox -e release
  artifacts:
    paths:
    - dist
  only:
    - tags
